"""Initial Migration

Revision ID: 1d2ece28fde7
Revises: 
Create Date: 2020-07-18 03:02:25.949782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2ece28fde7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('place', sa.UnicodeText(), nullable=True),
    sa.Column('country', sa.Unicode(length=50), nullable=True),
    sa.Column('city', sa.Unicode(length=50), nullable=True),
    sa.Column('distance', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Unicode(length=100), nullable=True),
    sa.Column('first_name', sa.Unicode(length=50), nullable=True),
    sa.Column('last_name', sa.Unicode(length=50), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('birth_date', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('visits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('location', sa.BigInteger(), nullable=True),
    sa.Column('user', sa.BigInteger(), nullable=True),
    sa.Column('visited_at', sa.BigInteger(), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
